### PR TITLE
Resources tab display

### PR DESCRIPTION
**Pull request by khoivan88**
Hi,

Again, thank you for this useful resource and your continued effort to update the website, resources, as well as your effort to educate the community. I have been following MolSSI for a while.

Today, I was about to share a specific tab in the 'Resources' page (not the first tab, 'Programming') from MolSSI when I realized that I could not do that yet. I hope this pull request would help with that!

Khoi V.

### CODE REVIEW

**Comment by janash** [comment]
Thanks, I think that would be a nice feature. @jchen0506 - can you review this PR when it's done?

**Comment by khoivan88** [comment]
Thank you @janash . While the two ready commits already did what I wanted, I am working on the reducing the code repetition for the `resources.md`. I am not quite familiar with jekyll but I have been using 11ty (11ty.dev) as my static site generator and they have some similarities so I am trying to draw from that.

**Comment by jchen0506** [comment]
Sure  @janash. Just Let me know when it's done @khoivan88 and I'll review it ASAP.

**Comment by khoivan88** [comment]
@jchen0506, I am trying to reduce the code repetition, especially in the tab content, however, it seems that Jekyll automatically added `<pre><code>...</code></pre>` for each one, do you know why?

Context:
I moved all of the yaml files under `_data` into a subfolder, so all of the yaml files are in `_data/resources`, in `resources.md` page, I have this code block:
```html
...
<!-- Tab content -->

{% for item in site.data.resources %}
{% comment %}
{% endcomment %}
{% assign tab_id = item[0] | slugify %}
{% assign tab_content = item[1] %}

  <div id="{{ tab_id }}" class="tabcontent">
    {% for resource in tab_content %}
      <div class="resource-content">
        <h2>
          {%- if resource.link -%}
          <a class="headerLink" href="https://education.molssi.org/{{ resource.link }}" target="_blank">{{ resource.title }}</a>
          {%- endif -%}
          {%- if resource.full_link -%}
            <a class="headerLink" href="{{ resource.full_link }}" target="_blank">{{ resource.title }}</a>
          {%- endif -%}
        </h2>

        <p><strong>Description: </strong> {{ resource.description }}</p>

        {%- if resource.topics -%}
        <details>
          <summary>Workshop Topics</summary>
          {{ resource.topics }}
        </details>
        {%- endif -%}

        {%- if resource.link -%}
        <span>{% octicon book %}</span>  <a target="_blank" href="https://education.molssi.org/{{ resource.link }}">View Workshop Materials</a> |
        <span>{% octicon mark-github %}</span>  <a target="_blank" href="https://github.com/MolSSI-Education/{{ resource.link }}">View GitHub Repository</a>
        {%- endif -%}

        {%- if resource.full_link -%}
        <span>{% octicon book %}</span>  <a target="_blank" href="{{ resource.full_link }}">View Workshop Materials</a>
        {%- endif -%}

        {%- if resource.youtube -%}
        <span>| {% octicon device-camera-video %}</span> <a target="_blank" href={{resource.youtube}}> View Workshop Recording</a>
        {%- endif -%}

      </div>
    {% endfor %}

  </div>
{% endfor %}
```

Note: I cannot use the `{%include resource.html %}` code since it breaks the format for some reason.

Anyway, with the code above, all of the content of `<div class="resource-content">...</div>` is automatically put inside `<pre><code>` tag, like this: `<pre><code><div class="resource-content">...</div></code></pre>`.

Would you happen to know why this occured?

Thanks!

**Comment by jchen0506** [comment]
@khoivan88 Honestly I've never used these tags before. Through a quick search, <pre> tag defines a pre-fomated text. The text will be displayed exactly as written in the HTML source code. And the <code> tag will define a piece of computer code. These are both more like a HTML thing instead of Jekyll thing. Is that possible it happened due to some of the lint/fomating tools you have on your editor? Do you happen to encounter those tags? @janash

**Comment by khoivan88** [comment]
> @khoivan88 Honestly I've never used these tags before. Through a quick search, "<pre>" tag defines a pre-fomated text. The text will be displayed exactly as written in the HTML source code. And the "<code>" tag will define a piece of computer code. These are both more like a HTML thing instead of Jekyll thing. Is that possible it happened due to some of the lint/fomating tools you have on your editor? Do you happen to encounter those tags? @janash

As far as I know, these tags are automatically added by Jekyll. These tags are normally used, intentionally, when a developer want to display a codeblock, so that the static site generator and HTML ignore the code block and not try to process them. I am using github codespace with a forked project of MolSSI website so the environment should be identical?

**Comment by khoivan88** [comment]
@jchen0506 and @janash , I found out why, somewhere deep in the internet (https://talk.jekyllrb.com/t/rouge-inserts-pre-tag-and-highlights-code-in-index-html-for-loop/5945/2), somebody way smarter than I am pointed out that 4-space indentation in markdown signify a codeblock. Because of my obsession with indentation, it was the issue. By removing the indentation, I got it down!

I will have this PR finished soon. Sorry about the issue!

**Comment by jchen0506** [comment]
@khoivan88 Great! Glad to hear it is solved. I wouldn't have thought about that.

**Review by jchen0506 — APPROVED** [review]
Looks all good to me. Ready to merge. Thank you for your contribution.

**Comment by khoivan88** [comment]
@jchen0506 Thank you very much for your review. No problem at all. I hope this helps!

**Comment by janash** [comment]
Beautiful! Thanks so much! I had been thinking this would be an excellent website addition when I tweeted the other day. Thanks so much for implementing it!

**Comment by khoivan88** [comment]
> Beautiful! Thanks so much! I had been thinking this would be an excellent website addition when I tweeted the other day. Thanks so much for implementing it!

No problem at all. Now I can share the specific tab :D. I actually helped a couple of websites implemented this so it was not much work at all. The difference is that you are using Jekyll and it is fun to play with a little bit because I have not used it before. 

This might be a bit of work and since you already have the system, it might not be worthwhile to do it but 11ty seems to be have a leg up on jekyll in term of providing you with much more flexibility in term of templating. I have also just looked at the Maps and did not understand why a lot of the 2021 events were not on the maps. Turns out that you would need the the map coordinate. With 11ty, you can have a data file using NodeJS to pull in data from API or CMS and use it for build process. I guess a quick work around this would be the use of github action to automatically pulling in the coordinates on every github commit (not sure if there is github action to trigger for commit to a specific file)

Anyway, super useful website and thank you for this :)!

**Pull request merged**
